### ISSUE TITLE
what is param?

### ISSUE THREAD

**Issue by epogrebnyak** [kavvkon/power-merit-Eur#1]
https://github.com/kavvkon/power-merit-Eur/blob/c3ec24ebe90145ef59df594e32a3c5a780802b5f/merit_dash.py#L5

Is param a library?

**Comment by kavvkon** [comment]
Yes, see here https://panel.holoviz.org/user_guide/Param.html

**Comment by epogrebnyak** [comment]
Thanks for the link! Perhaps should add to requirements.txt?
